---
# Set necessary role variables

# Directories

- name: Set java installation directory on Debian platforms
  set_fact:
    java_install_dir: /usr/lib/jvm
    java_default_link_name: default-java
    java_home: /usr/lib/jvm/default-java
  when: ansible_os_family == "Debian"

- name: Set java installation directory on Mac OS X
  set_fact:
    # The Java installation directory on Mac OS X is determined by the package itself.
    java_install_dir: /no_such_directory
    java_default_link_name: default
  when: ansible_os_family == "Darwin"

- name: Set java installation directory on non-Debian platforms
  set_fact:
    java_install_dir: /usr/java
    java_default_link_name: default
    java_home: /usr/java/default
  when: ansible_os_family != "Debian" and ansible_os_family != "Darwin"
